
datasource:
  h2:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  mysql:
    url: jdbc:mysql://localhost:6603/testedb?createDatabaseIfNotExist=true
    username: root
    password: 123
    driverClassName: com.mysql.cj.jdbc.Driver
